#!/usr/bin/env python3
"""Subset and convert Whitney OTFs into web fonts.

Whitney is a licensed typeface from Hoefler & Co. The source OTFs live outside
this repo and the generated .woff2 files are gitignored; this script rebuilds
them from a local font library.

    python3 scripts/build-fonts.py [--src "/path/to/font/folder"]
"""

import argparse
import pathlib
import sys

from fontTools.subset import main as subset_main

DEFAULT_SRC = pathlib.Path.home() / "Fonts" / "Master Library"
OUT = pathlib.Path(__file__).resolve().parent.parent / "web" / "fonts"

# Latin text, typographic punctuation, arrows, and the few symbols the UI uses.
UNICODES = (
    "U+0020-007E,U+00A0-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,"
    "U+02DC,U+2000-206F,U+20AC,U+2122,U+2190-21BB,U+2212,U+2215,U+FEFF,U+FFFD"
)

# (source file, output name, css family, weight, style)
FACES = [
    # Whitney Pro — display and headline sizes
    ("Whitney-Light-ProGkCy.otf",     "whitney-light",        "Whitney", 300, "normal"),
    ("Whitney-Book-ProGkCy.otf",      "whitney-book",         "Whitney", 400, "normal"),
    ("Whitney-BookItal-ProGkCy.otf",  "whitney-book-italic",  "Whitney", 400, "italic"),
    ("Whitney-Medium-ProGkCy.otf",    "whitney-medium",       "Whitney", 500, "normal"),
    ("Whitney-Semibld-ProGkCy.otf",   "whitney-semibold",     "Whitney", 600, "normal"),
    ("Whitney-Bold-ProGkCy.otf",      "whitney-bold",         "Whitney", 700, "normal"),
    # Whitney ScreenSmart — small on-screen text
    ("WhitneySSm-Book.otf",           "whitney-ssm-book",     "Whitney SSm", 400, "normal"),
    ("WhitneySSm-Medium.otf",         "whitney-ssm-medium",   "Whitney SSm", 500, "normal"),
    ("WhitneySSm-Semibold.otf",       "whitney-ssm-semibold", "Whitney SSm", 600, "normal"),
    # Whitney Condensed — labels and wayfinding-style caps
    ("WhitneyCond-Medium.otf",        "whitney-cond-medium",  "Whitney Cond", 500, "normal"),
    ("WhitneyCond-Semibold.otf",      "whitney-cond-semibold","Whitney Cond", 600, "normal"),
]

CSS_HEADER = """/* Generated by scripts/build-fonts.py — do not edit by hand.
   Whitney © Hoefler & Co. Subset to Latin + punctuation for local use. */

"""

# Metric-matched fallbacks. Whitney loads from the same origin and is
# preloaded, but any swap at all reflows the page unless the fallback carries
# Whitney's own vertical metrics and x-height. One per family, computed from
# the real font rather than guessed. Reference x-heights are Helvetica Neue's.
FALLBACKS = [
    ("Whitney Fallback", "Whitney-Book-ProGkCy.otf"),
    ("Whitney SSm Fallback", "WhitneySSm-Book.otf"),
    ("Whitney Cond Fallback", "WhitneyCond-Medium.otf"),
]
REFERENCE_X_HEIGHT = 0.517  # Helvetica Neue, normalised to its em


def fallback_css(family, source):
    """@font-face for a local face overridden to match `source`'s metrics."""
    from fontTools.ttLib import TTFont

    font = TTFont(source, lazy=True)
    upem = font["head"].unitsPerEm
    hhea = font["hhea"]
    x_height = font["OS/2"].sxHeight / upem
    ascent = hhea.ascent / upem
    descent = abs(hhea.descent) / upem
    line_gap = hhea.lineGap / upem
    font.close()

    # scale the stand-in until its x-height matches, then restate the vertical
    # metrics relative to that scale so the line box is identical either way
    size_adjust = x_height / REFERENCE_X_HEIGHT
    return (
        "@font-face {\n"
        f'  font-family: "{family}";\n'
        '  src: local("Helvetica Neue"), local("Arial"), local("Liberation Sans");\n'
        f"  size-adjust: {size_adjust * 100:.2f}%;\n"
        f"  ascent-override: {ascent / size_adjust * 100:.2f}%;\n"
        f"  descent-override: {descent / size_adjust * 100:.2f}%;\n"
        f"  line-gap-override: {line_gap / size_adjust * 100:.2f}%;\n"
        "}\n\n"
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=str(DEFAULT_SRC))
    args = ap.parse_args()
    src = pathlib.Path(args.src).expanduser()

    if not src.is_dir():
        sys.exit(f"font source folder not found: {src}")

    OUT.mkdir(parents=True, exist_ok=True)
    css = [CSS_HEADER]
    total = 0

    for filename, slug, family, weight, style in FACES:
        source = src / filename
        if not source.exists():
            sys.exit(f"missing {source}")
        dest = OUT / f"{slug}.woff2"
        subset_main([
            str(source),
            f"--unicodes={UNICODES}",
            # Real H&Co devices: true small caps, old-style and tabular figures,
            # superiors for the Nº, fractions. Retaining a feature also retains
            # the glyphs it reaches, so the small-cap alphabet survives subsetting.
            "--layout-features=kern,liga,clig,calt,smcp,c2sc,onum,lnum,pnum,tnum,"
            "sups,subs,numr,dnom,frac,sinf,ss01,ss02,salt",
            "--flavor=woff2",
            "--no-hinting",
            "--desubroutinize",
            f"--output-file={dest}",
        ])
        size = dest.stat().st_size
        total += size
        print(f"  {dest.name:<26} {size / 1024:6.1f} KB")
        css.append(
            "@font-face {\n"
            f'  font-family: "{family}";\n'
            f"  font-style: {style};\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f'  src: url("fonts/{slug}.woff2") format("woff2");\n'
            "}\n\n"
        )

    fallbacks = "".join(fallback_css(family, src / filename) for family, filename in FALLBACKS)
    css.append("/* Metric-matched fallbacks — see fallback_css(). */\n\n" + fallbacks)
    (OUT.parent / "fonts.css").write_text("".join(css))

    # The public deploy cannot carry Whitney, so it ships these alone: local
    # Helvetica/Arial restated to Whitney's metrics. Numbers, not font data,
    # which is why this file is committed and fonts.css is not.
    (OUT.parent / "fonts.fallback.css").write_text(
        "/* Generated by scripts/build-fonts.py. Metric-matched local fallbacks only —\n"
        "   no font data. Served in place of fonts.css wherever Whitney is not. */\n\n"
        + fallbacks
    )
    print("wrote web/fonts.fallback.css")
    print(f"\n{len(FACES)} faces, {total / 1024:.0f} KB total → web/fonts/")
    print("wrote web/fonts.css")


if __name__ == "__main__":
    main()
