#!/usr/bin/env node
/**
 * Project the city into the map's own 1000x1000 space.
 *
 *   npm run city        data/*.json  ->  web/city.js
 *
 * Web Mercator, fitted to the borough bounds with a small margin, so the
 * whole of New York sits inside a square the app can reason about without
 * carrying a projection library. The street network in web/streets.js is
 * fitted the same way by scripts/build-streets.mjs — the two must agree,
 * which is why both read their frame from data/boroughs.json.
 */

import { readFile, writeFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)
const read = async (f) => JSON.parse(await readFile(new URL(f, root), 'utf8'))

const W = 1000, H = 1000, PAD = 26
const merc = ([lng, lat]) => [lng, (Math.log(Math.tan(Math.PI / 4 + (lat * Math.PI / 180) / 2)) * 180) / Math.PI]

const geo = await read('data/boroughs.json')
const museums = await read('data/museums.json')

let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity
for (const f of geo.features)
  for (const poly of f.geometry.coordinates)
    for (const ring of poly)
      for (const pt of ring) {
        const [x, y] = merc(pt)
        if (x < x0) x0 = x; if (x > x1) x1 = x
        if (y < y0) y0 = y; if (y > y1) y1 = y
      }

const s = Math.min((W - PAD * 2) / (x1 - x0), (H - PAD * 2) / (y1 - y0))
const ox = (W - (x1 - x0) * s) / 2, oy = (H - (y1 - y0) * s) / 2
const put = (p) => { const [x, y] = merc(p); return [(x - x0) * s + ox, (y1 - y) * s + oy] }
const r1 = (n) => Math.round(n * 10) / 10

// one path per borough: every ring of every polygon, closed
const LAND = geo.features.map((f) => {
  let d = ''
  for (const poly of f.geometry.coordinates)
    for (const ring of poly) {
      d += ring.map((pt, i) => { const [x, y] = put(pt); return `${i ? 'L' : 'M'}${r1(x)} ${r1(y)}` }).join('')
      d += 'Z'
    }
  return { n: f.properties.boro_name ?? f.properties.BoroName ?? f.properties.name, d }
})

// The index reads A-Z. The dataset is kept in whatever order it was
// curated in, so the sort belongs here rather than in the data file.
const M = [...museums].sort((a, b) => a.name.localeCompare(b.name, 'en')).map((m) => {
  const [x, y] = put([m.lng, m.lat])
  return {
    i: m.id, n: m.name, b: m.borough, h: m.neighborhood ?? '',
    a: m.address.split(',')[0].trim(),         // the street line, for the index
    f: m.address,                              // the whole thing, for the card
    c: m.category, u: m.url ?? '',
    x: r1(x), y: r1(y), lat: m.lat, lng: m.lng,
  }
})

const out = `/* Generated by scripts/build-city.mjs from data/boroughs.json and
   data/museums.json. Do not edit by hand: run \`npm run city\`.
   Boroughs: NYC Department of City Planning. Coordinates: OpenStreetMap. */
const LAND=${JSON.stringify(LAND)};
const M=${JSON.stringify(M)};
const VIEW={w:${W},h:${H}};
`
await writeFile(new URL('web/city.js', root), out)
console.log(`web/city.js — ${LAND.length} boroughs, ${M.length} museums, ${(out.length / 1024) | 0} KB`)
